-- User
SELECT TOP (1000) [Id]
      ,[Name]
      ,[UserName]
      ,[NormalizedUserName]
      ,[Email]
      ,[NormalizedEmail]
      ,[EmailConfirmed]
      ,[PasswordHash]
      ,[SecurityStamp]
      ,[ConcurrencyStamp]
      ,[PhoneNumber]
      ,[PhoneNumberConfirmed]
      ,[TwoFactorEnabled]
      ,[LockoutEnd]
      ,[LockoutEnabled]
      ,[AccessFailedCount]
      ,[AvatarUrl]
      ,[Bio]
  FROM [HachimiDatabase].[dbo].[AppUsers]

SELECT TOP (1000) [UserId]
      ,[RoleId]
  FROM [HachimiDatabase].[dbo].[AppUserRoles]

  DELETE FROM [HachimiDatabase].[dbo].[AppUserRoles]
  DELETE FROM [HachimiDatabase].[dbo].AppUsers

  SELECT TOP (1000) [Id]
      ,[Description]
      ,[RoleCode]
      ,[Name]
      ,[NormalizedName]
      ,[ConcurrencyStamp]
  FROM [HachimiDatabase].[dbo].[AppRoles]
